### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by camdez** [anthonygalea/notes-on-clojure#1]
First off, this is an awesome set of notes. Very nicely done!

I ran across a few small typos (since they're all trivial to fix, I figured I wouldn't bother you with a bunch of separate issues):

https://github.clerk.garden/anthonygalea/notes-on-clojure/commit/1f7a15e4de6b61c363185691b340c74c95412f04/notebooks/maps/#select-keys

> Sometimes we want a map containing only some of the entries in another map:

Probably should say something like "containing only the entries with keys in a certain *collection*"

---

https://github.clerk.garden/anthonygalea/notes-on-clojure/commit/1f7a15e4de6b61c363185691b340c74c95412f04/notebooks/maps/#update-keys

>Note that this is not recursive. If that's what you want see keywordize-keys below.

s/keywordize-keys/stringify-keys/

---

https://github.clerk.garden/anthonygalea/notes-on-clojure/commit/1f7a15e4de6b61c363185691b340c74c95412f04/notebooks/sequences/#realized?

Two small issues here:

1. `rand-int` requires an argument, hence the first code sample actually only evaluates because it's not realized.
2. The latter two code samples show incorrect values, perhaps owing to  number 1.

**Comment by anthonygalea** [comment]
> First off, this is an awesome set of notes. Very nicely done!

Thanks!

> Probably should say something like "containing only the entries with keys in a certain _collection_"

I'm not sure I follow what's confusing in this one. AFAIK `select-keys` should only be used with a map, not *any* collection. Or perhaps by _collection_ you mean the vector of keywords?

Perhaps you find the phrasing confusing because I wrote both "a map" and "another map" in the same sentence? If that's the case what do you think about changing:
`Sometimes we want a map containing only some of the entries in another map:`
to:
`Sometimes we only want some of the entries of a map:`

> s/keywordize-keys/stringify-keys/

👍 covered in 6c726899189a8f7dab2dd2305bb0ef3ffe34933e

Thanks for pointing out regarding `realized?`, given the existing example just brought confusion I opted to drop it for now 4a4e2f4cd115760be3d934e2737d5910eb89c0b0

**Comment by camdez** [comment]
Ahhh, now I understand how the `select-keys` text was meant.

In terms of the `select-keys` argument names (`[map keyseq]`), I thought you were saying "Sometimes we want a map containing only some of the entries in another map [`keyseq`]", as if that second argument were itself a map.

After looking at it again, my reading didn't make sense, but I think your updated wording above is an improvement.
